import moment from 'moment'
export default {
    info: {
        applyUserId: "",
        applyUserName: "",
        applyDepartCode: '',
        applyDepartName: '',
        useDate: '',
        applyCategoryCode: '',
        applyCategoryName: "",
        budgetValidEnumName: "",
        budgetProjectName: "",
        applyDate: moment().format('YYYY-MM-DD'),
        formStatus: "",
        receiptTypeEnumId: "",
        receiptTypeEnumName: '',
        applyAmount: 0,
        receiptStartDate: '',
        receiptEndDate: "",
        receiptStandardEnumId: "",
        receiptStandardEnumName: '',
        receiptNum: 0,
        companyNum: 0,
        totalNum: 0,
        entertainmentDetailList: [],
        reason: '',
        receiptCompanyName: "",
        receiptLocation: "",
        receiptContentEnumId: "",
        receiptContentEnumName: ""
    },
}
